### ISSUE TITLE
Output as a file

### ISSUE THREAD

**Issue by StrangeTcy** [m13253/lvdo#6]
I'm sorry, but can you write an example of outputting the decoded data into a file. I guess it should be -o secret.mp3 somewhere in the line, but I can't figure out where exactly.

**Comment by m13253** [comment]
I am sorry that I have not said it clearly.
Use the pipe `> secret.mp3` to redirect the output to a file will work.
Like this:
```bash
ffmpeg -i public.mkv -r 1 -f rawvideo - | ./lvdodec -s 640x480 -q 6 --qmin 1 --qmax 4 > secret.mp3
```

**Comment by StrangeTcy** [comment]
Thanks! Although the decoding results in a lot of warnings about clipping -1 to 0, but that's another issue.

**Comment by StrangeTcy** [comment]
Not an issue, just a comment: I tried encoding and then decoding a .pdf, and it got restored as file of the same size, but opening it resulting in a "damaged pdf" error.

**Comment by m13253** [comment]
Yes. That was because there is no error detection and recovery.
It would be better if something like "WinRAR self fix archive" could be implemented on top of it.

But currently I do not have enough time to work on this project. Feel free if anyone can help improve this.
